name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

      # Step 4: Run Playwright tests and save reports
      - name: Run Playwright tests
        run: |
          mkdir -p test-results/screenshots test-results/videos
          pytest --maxfail=1 --disable-warnings --tb=short --capture=sys \
          --html=test-results/report.html --self-contained-html || true

      # Step 5: Upload artifacts (screenshots, videos, reports)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts
          path: test-results/
