<<<<<<< HEAD
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Playwright Tests

# Trigger workflow on push or PR to main
=======
name: Playwright Tests

>>>>>>> b67e5da (Add GitHub Actions workflow for Playwright tests)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # adjust to your version

      # Step 3: Install dependencies
=======
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

>>>>>>> b67e5da (Add GitHub Actions workflow for Playwright tests)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

<<<<<<< HEAD
      # Step 4: Run Playwright tests
      - name: Run Playwright tests
        run: |
          pytest --headed --maxfail=1 --disable-warnings

=======
      - name: Run Playwright tests
        run: |
          pytest
>>>>>>> b67e5da (Add GitHub Actions workflow for Playwright tests)
